version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    target-branch: "deps"
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - Sh4bbY
    assignees:
      - Sh4bbY
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "deps"
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - Sh4bbY
    assignees:
      - Sh4bbY
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
